service: slack-app-serverless
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  environment: ${file(./utils/secretsManager.js):getSecrets}
functions:
  events:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
  oauth:
    handler: app.oauthHandler
    events:
      - http:
          path: slack/oauth_redirect
          method: get            
      - http:
          path: slack/install
          method: get
plugins:
  - serverless-offline